[buildOptions]
optimizeWithTtx = false

[buildPlans.sans]  # based on Iosevka Aile
family  = "Nowar DIN LCG"
design  = ["type", "v-at-fourfold", "v-j-narrow", 'v-capital-i-straight', 'v-capital-j-straight', 'v-g-singlestorey', 'v-r-narrow', "no-cv-ss", "no-ligation"]
upright = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']

[buildPlans.sans.post]
design = ["diversity-2"]

[buildPlans.cursive]  # based on Iosevka Sparkle
family  = "Nowar DIN Cursive LCG"
design  = ["type", "s-cursive", "v-at-fourfold", "v-j-narrow-serifed", "v-w-curly", "no-cv-ss", "no-ligation"]
upright = ['v-i-italic', 'v-l-italic', "v-f-tailed", 'v-r-top-serifed']

[buildPlans.cursive.post]
design = ["diversity-1"]

[weights.light]
shape = 280
menu  = 300
css   = 300

[weights.regular]
shape = 405
menu  = 400
css   = 400

[weights.medium]
shape = 520
menu  = 500
css   = 500

[weights.bold]
shape = 750
menu  = 700
css   = 700

[slants]
upright = "normal"

[widths.condensed]
shape = 440
menu  = 3
css   = "condensed"

[widths.normal]
shape = 500
menu  = 5
css   = "normal"

[widths.extended]
shape = 560
menu  = 7
css   = "expanded"
